# Generated by Django 3.2 on 2021-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=12, unique=True)),
                ('photo', models.ImageField(upload_to='uploads/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
